package com.jaio360.domain;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA

import com.jaio360.orm.*;
import java.util.Date;

/**
 * Proyecto generated by hbm2java
 */
public class LastUpdateBean implements java.io.Serializable {

    private Integer luIdUpdatePk;
    private String luTxTipo;
    private Date luDtFecha;
    private String luTxDescripcion;
    private String strColor;
    private String strIcon;

    public String getStrIcon() {
        return strIcon;
    }

    public void setStrIcon(String strIcon) {
        this.strIcon = strIcon;
    }

    
    public String getStrColor() {
        return strColor;
    }

    public void setStrColor(String strColor) {
        this.strColor = strColor;
    }

    public LastUpdateBean() {
    }

    public Integer getLuIdUpdatePk() {
        return luIdUpdatePk;
    }

    public void setLuIdUpdatePk(Integer luIdUpdatePk) {
        this.luIdUpdatePk = luIdUpdatePk;
    }

    public String getLuTxTipo() {
        return luTxTipo;
    }

    public void setLuTxTipo(String luTxTipo) {
        this.luTxTipo = luTxTipo;
    }

    public Date getLuDtFecha() {
        return luDtFecha;
    }

    public void setLuDtFecha(Date luDtFecha) {
        this.luDtFecha = luDtFecha;
    }

    public String getLuTxDescripcion() {
        return luTxDescripcion;
    }

    public void setLuTxDescripcion(String luTxDescripcion) {
        this.luTxDescripcion = luTxDescripcion;
    }

}
