package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer coIdContratoPk;
     private Usuario usuario;
     private Tarifa tarifa;
     private String coIdTipoContrato;
     private Date coFeCreacion;
     private Integer coNuLicenciaTotal;
     private Integer coNuLicenciaDisponible;
     private Date coFeCulminacion;
     private Integer coIdEstado;

    public Contrato() {
    }

	
    public Contrato(Usuario usuario, Tarifa tarifa, String coIdTipoContrato, Date coFeCreacion, Integer coNuLicenciaTotal, Integer coNuLicenciaDisponible, Integer coIdEstado) {
        this.usuario = usuario;
        this.tarifa = tarifa;
        this.coIdTipoContrato = coIdTipoContrato;
        this.coFeCreacion = coFeCreacion;
        this.coNuLicenciaTotal = coNuLicenciaTotal;
        this.coNuLicenciaDisponible = coNuLicenciaDisponible;
        this.coIdEstado = coIdEstado;
    }
    public Contrato(Usuario usuario, Tarifa tarifa, String coIdTipoContrato, Date coFeCreacion, Integer coNuLicenciaTotal, Integer coNuLicenciaDisponible, Date coFeCulminacion, Integer coIdEstado) {
       this.usuario = usuario;
       this.tarifa = tarifa;
       this.coIdTipoContrato = coIdTipoContrato;
       this.coFeCreacion = coFeCreacion;
       this.coNuLicenciaTotal = coNuLicenciaTotal;
       this.coNuLicenciaDisponible = coNuLicenciaDisponible;
       this.coFeCulminacion = coFeCulminacion;
       this.coIdEstado = coIdEstado;
    }
   
    public Integer getCoIdContratoPk() {
        return this.coIdContratoPk;
    }
    
    public void setCoIdContratoPk(Integer coIdContratoPk) {
        this.coIdContratoPk = coIdContratoPk;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Tarifa getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(Tarifa tarifa) {
        this.tarifa = tarifa;
    }
    public String getCoIdTipoContrato() {
        return this.coIdTipoContrato;
    }
    
    public void setCoIdTipoContrato(String coIdTipoContrato) {
        this.coIdTipoContrato = coIdTipoContrato;
    }
    public Date getCoFeCreacion() {
        return this.coFeCreacion;
    }
    
    public void setCoFeCreacion(Date coFeCreacion) {
        this.coFeCreacion = coFeCreacion;
    }
    public Integer getCoNuLicenciaTotal() {
        return this.coNuLicenciaTotal;
    }
    
    public void setCoNuLicenciaTotal(Integer coNuLicenciaTotal) {
        this.coNuLicenciaTotal = coNuLicenciaTotal;
    }
    public Integer getCoNuLicenciaDisponible() {
        return this.coNuLicenciaDisponible;
    }
    
    public void setCoNuLicenciaDisponible(Integer coNuLicenciaDisponible) {
        this.coNuLicenciaDisponible = coNuLicenciaDisponible;
    }
    public Date getCoFeCulminacion() {
        return this.coFeCulminacion;
    }
    
    public void setCoFeCulminacion(Date coFeCulminacion) {
        this.coFeCulminacion = coFeCulminacion;
    }
    public Integer getCoIdEstado() {
        return this.coIdEstado;
    }
    
    public void setCoIdEstado(Integer coIdEstado) {
        this.coIdEstado = coIdEstado;
    }




}


