package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA



/**
 * CuestionarioEvaluado generated by hbm2java
 */
public class CuestionarioEvaluado  implements java.io.Serializable {


     private CuestionarioEvaluadoId id;
     private Integer ceIdEstado;
     private Cuestionario cuestionario;
     private Participante participante;
     private Proyecto proyecto;

    public CuestionarioEvaluado() {
    }

    public CuestionarioEvaluado(CuestionarioEvaluadoId id, Integer ceIdEstado, Cuestionario cuestionario, Participante participante, Proyecto proyecto) {
       this.id = id;
       this.cuestionario = cuestionario;
       this.participante = participante;
       this.proyecto = proyecto;
       this.ceIdEstado = ceIdEstado;
    }
   
    public CuestionarioEvaluadoId getId() {
        return this.id;
    }
    
    public void setId(CuestionarioEvaluadoId id) {
        this.id = id;
    }
    public Cuestionario getCuestionario() {
        return this.cuestionario;
    }
    
    public Integer getCeIdEstado() {
        return this.ceIdEstado;
    }
    
    public void setCeIdEstado(Integer ceIdEstado) {
        this.ceIdEstado = ceIdEstado;
    }

    public void setCuestionario(Cuestionario cuestionario) {
        this.cuestionario = cuestionario;
    }
    public Participante getParticipante() {
        return this.participante;
    }
    
    public void setParticipante(Participante participante) {
        this.participante = participante;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }




}


