package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA



/**
 * CuestionarioEvaluadoId generated by hbm2java
 */
public class CuestionarioEvaluadoId  implements java.io.Serializable {


     private Integer cuIdCuestionarioFk;
     private Integer paIdParticipanteFk;
     private Integer poIdProyectoFk;

    public CuestionarioEvaluadoId() {
    }

    public CuestionarioEvaluadoId(Integer cuIdCuestionarioFk, Integer paIdParticipanteFk, Integer poIdProyectoFk) {
       this.cuIdCuestionarioFk = cuIdCuestionarioFk;
       this.paIdParticipanteFk = paIdParticipanteFk;
       this.poIdProyectoFk = poIdProyectoFk;
    }
   
    public Integer getCuIdCuestionarioFk() {
        return this.cuIdCuestionarioFk;
    }
    
    public void setCuIdCuestionarioFk(Integer cuIdCuestionarioFk) {
        this.cuIdCuestionarioFk = cuIdCuestionarioFk;
    }
    public Integer getPaIdParticipanteFk() {
        return this.paIdParticipanteFk;
    }
    
    public void setPaIdParticipanteFk(Integer paIdParticipanteFk) {
        this.paIdParticipanteFk = paIdParticipanteFk;
    }
    public Integer getPoIdProyectoFk() {
        return this.poIdProyectoFk;
    }
    
    public void setPoIdProyectoFk(Integer poIdProyectoFk) {
        this.poIdProyectoFk = poIdProyectoFk;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CuestionarioEvaluadoId) ) return false;
		 CuestionarioEvaluadoId castOther = ( CuestionarioEvaluadoId ) other; 
         
		 return (this.getCuIdCuestionarioFk()==castOther.getCuIdCuestionarioFk())
 && (this.getPaIdParticipanteFk()==castOther.getPaIdParticipanteFk())
 && (this.getPoIdProyectoFk()==castOther.getPoIdProyectoFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCuIdCuestionarioFk();
         result = 37 * result + this.getPaIdParticipanteFk();
         result = 37 * result + this.getPoIdProyectoFk();
         return result;
   }   


}


