package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DefinicionTabla generated by hbm2java
 */
public class DefinicionTabla  implements java.io.Serializable {


     private Integer dtIdDefinicionPk;
     private String dtTxDescripcion;
     private String dtTxComentario;
     private Set elementos = new HashSet(0);

    public DefinicionTabla() {
    }

	
    public DefinicionTabla(String dtTxDescripcion) {
        this.dtTxDescripcion = dtTxDescripcion;
    }
    public DefinicionTabla(String dtTxDescripcion, String dtTxComentario, Set elementos) {
       this.dtTxDescripcion = dtTxDescripcion;
       this.dtTxComentario = dtTxComentario;
       this.elementos = elementos;
    }
   
    public Integer getDtIdDefinicionPk() {
        return this.dtIdDefinicionPk;
    }
    
    public void setDtIdDefinicionPk(Integer dtIdDefinicionPk) {
        this.dtIdDefinicionPk = dtIdDefinicionPk;
    }
    public String getDtTxDescripcion() {
        return this.dtTxDescripcion;
    }
    
    public void setDtTxDescripcion(String dtTxDescripcion) {
        this.dtTxDescripcion = dtTxDescripcion;
    }
    public String getDtTxComentario() {
        return this.dtTxComentario;
    }
    
    public void setDtTxComentario(String dtTxComentario) {
        this.dtTxComentario = dtTxComentario;
    }
    public Set getElementos() {
        return this.elementos;
    }
    
    public void setElementos(Set elementos) {
        this.elementos = elementos;
    }




}


