package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA



/**
 * Destinatarios generated by hbm2java
 */
public class Destinatarios  implements java.io.Serializable {


     private Integer deIdDestinatarioPk;
     private Notificaciones notificaciones;
     private String deTxMail;
     private String deTxMailCc;
     

    public Destinatarios() {
    }

    public Destinatarios(Notificaciones notificaciones, String deTxMail, String deTxMailCc) {
       this.notificaciones = notificaciones;
       this.deTxMail = deTxMail;
       this.deTxMailCc = deTxMailCc;
    }
   
    public Integer getDeIdDestinatarioPk() {
        return this.deIdDestinatarioPk;
    }

    public String getDeTxMailCc() {
        return deTxMailCc;
    }

    public void setDeTxMailCc(String deTxMailCc) {
        this.deTxMailCc = deTxMailCc;
    }
    
    public void setDeIdDestinatarioPk(Integer deIdDestinatarioPk) {
        this.deIdDestinatarioPk = deIdDestinatarioPk;
    }
    public Notificaciones getNotificaciones() {
        return this.notificaciones;
    }
    
    public void setNotificaciones(Notificaciones notificaciones) {
        this.notificaciones = notificaciones;
    }
    public String getDeTxMail() {
        return this.deTxMail;
    }
    
    public void setDeTxMail(String deTxMail) {
        this.deTxMail = deTxMail;
    }




}


