package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HistorialAcceso generated by hbm2java
 */
public class HistorialAcceso  implements java.io.Serializable {


     private Integer haIdHistorialPk;
     private Usuario usuario;
     private Date haFeIngreso;
     private Date haFeSalida;
     private boolean haInEstado;

    public HistorialAcceso() {
    }

	
    public HistorialAcceso(Usuario usuario, Date haFeIngreso, boolean haInEstado) {
        this.usuario = usuario;
        this.haFeIngreso = haFeIngreso;
        this.haInEstado = haInEstado;
    }
    public HistorialAcceso(Usuario usuario, Date haFeIngreso, Date haFeSalida, boolean haInEstado) {
       this.usuario = usuario;
       this.haFeIngreso = haFeIngreso;
       this.haFeSalida = haFeSalida;
       this.haInEstado = haInEstado;
    }
   
    public Integer getHaIdHistorialPk() {
        return this.haIdHistorialPk;
    }
    
    public void setHaIdHistorialPk(Integer haIdHistorialPk) {
        this.haIdHistorialPk = haIdHistorialPk;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHaFeIngreso() {
        return this.haFeIngreso;
    }
    
    public void setHaFeIngreso(Date haFeIngreso) {
        this.haFeIngreso = haFeIngreso;
    }
    public Date getHaFeSalida() {
        return this.haFeSalida;
    }
    
    public void setHaFeSalida(Date haFeSalida) {
        this.haFeSalida = haFeSalida;
    }
    public boolean isHaInEstado() {
        return this.haInEstado;
    }
    
    public void setHaInEstado(boolean haInEstado) {
        this.haInEstado = haInEstado;
    }




}


