package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje implements java.io.Serializable {

    private Integer meIdMensajePk;
    private Proyecto proyecto;
    private Integer meIdTipoMensaje;
    private String meTxAsunto;
    private byte[] meTxCuerpo;
    private byte[] meTxConvocatoriaTitulo;
    private byte[] meTxConvocatoriaParrafo;
    private byte[] meTxConvocatoriaURL;
    private byte[] meTxBienvenidaRecomendacion;
    private byte[] meTxBienvenidaConfidencialidad;
    private byte[] meTxBienvenidaAgradecimiento;
    private byte[] meTxAgradecimiento;

    public byte[] getMeTxAgradecimiento() {
        return meTxAgradecimiento;
    }

    public void setMeTxAgradecimiento(byte[] meTxAgradecimiento) {
        this.meTxAgradecimiento = meTxAgradecimiento;
    }

    public byte[] getMeTxBienvenidaRecomendacion() {
        return meTxBienvenidaRecomendacion;
    }

    public byte[] getMeTxConvocatoriaURL() {
        return meTxConvocatoriaURL;
    }

    public void setMeTxConvocatoriaURL(byte[] meTxConvocatoriaURL) {
        this.meTxConvocatoriaURL = meTxConvocatoriaURL;
    }
    
    public void setMeTxBienvenidaRecomendacion(byte[] meTxBienvenidaRecomendacion) {
        this.meTxBienvenidaRecomendacion = meTxBienvenidaRecomendacion;
    }

    public byte[] getMeTxBienvenidaConfidencialidad() {
        return meTxBienvenidaConfidencialidad;
    }

    public void setMeTxBienvenidaConfidencialidad(byte[] meTxBienvenidaConfidencialidad) {
        this.meTxBienvenidaConfidencialidad = meTxBienvenidaConfidencialidad;
    }

    public byte[] getMeTxBienvenidaAgradecimiento() {
        return meTxBienvenidaAgradecimiento;
    }

    public void setMeTxBienvenidaAgradecimiento(byte[] meTxBienvenidaAgradecimiento) {
        this.meTxBienvenidaAgradecimiento = meTxBienvenidaAgradecimiento;
    }

    public Mensaje() {
    }

    public Mensaje(Proyecto proyecto, int meIdTipoMensaje) {
        this.proyecto = proyecto;
        this.meIdTipoMensaje = meIdTipoMensaje;
    }

    public Mensaje(Proyecto proyecto, int meIdTipoMensaje, String meTxAsunto, byte[] meTxCuerpo) {
        this.proyecto = proyecto;
        this.meIdTipoMensaje = meIdTipoMensaje;
        this.meTxAsunto = meTxAsunto;
        this.meTxCuerpo = meTxCuerpo;
    }

    public byte[] getMeTxConvocatoriaTitulo() {
        return meTxConvocatoriaTitulo;
    }

    public void setMeTxConvocatoriaTitulo(byte[] meTxConvocatoriaTitulo) {
        this.meTxConvocatoriaTitulo = meTxConvocatoriaTitulo;
    }

    public byte[] getMeTxConvocatoriaParrafo() {
        return meTxConvocatoriaParrafo;
    }

    public void setMeTxConvocatoriaParrafo(byte[] meTxConvocatoriaParrafo) {
        this.meTxConvocatoriaParrafo = meTxConvocatoriaParrafo;
    }

    public Integer getMeIdMensajePk() {
        return this.meIdMensajePk;
    }

    public void setMeIdMensajePk(Integer meIdMensajePk) {
        this.meIdMensajePk = meIdMensajePk;
    }

    public Proyecto getProyecto() {
        return this.proyecto;
    }

    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    public Integer getMeIdTipoMensaje() {
        return this.meIdTipoMensaje;
    }

    public void setMeIdTipoMensaje(Integer meIdTipoMensaje) {
        this.meIdTipoMensaje = meIdTipoMensaje;
    }

    public String getMeTxAsunto() {
        return this.meTxAsunto;
    }

    public void setMeTxAsunto(String meTxAsunto) {
        this.meTxAsunto = meTxAsunto;
    }

    public byte[] getMeTxCuerpo() {
        return this.meTxCuerpo;
    }

    public void setMeTxCuerpo(byte[] meTxCuerpo) {
        this.meTxCuerpo = meTxCuerpo;
    }

}
