package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Metrica generated by hbm2java
 */
public class Metrica  implements java.io.Serializable {


     private Integer meIdMetricaPk;
     private Proyecto proyecto;
     private int meIdTipoMetrica;
     private Date meFeRegistro;
     private int meNuRango;
     private Set detalleMetricas = new HashSet(0);

    public Metrica() {
    }

	
    public Metrica(Proyecto proyecto, int meIdTipoMetrica, Date meFeRegistro, int meNuRango) {
        this.proyecto = proyecto;
        this.meIdTipoMetrica = meIdTipoMetrica;
        this.meFeRegistro = meFeRegistro;
        this.meNuRango = meNuRango;
    }
    public Metrica(Proyecto proyecto, int meIdTipoMetrica, Date meFeRegistro, int meNuRango, Set detalleMetricas) {
       this.proyecto = proyecto;
       this.meIdTipoMetrica = meIdTipoMetrica;
       this.meFeRegistro = meFeRegistro;
       this.meNuRango = meNuRango;
       this.detalleMetricas = detalleMetricas;
    }
   
    public Integer getMeIdMetricaPk() {
        return this.meIdMetricaPk;
    }
    
    public void setMeIdMetricaPk(Integer meIdMetricaPk) {
        this.meIdMetricaPk = meIdMetricaPk;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public int getMeIdTipoMetrica() {
        return this.meIdTipoMetrica;
    }
    
    public void setMeIdTipoMetrica(int meIdTipoMetrica) {
        this.meIdTipoMetrica = meIdTipoMetrica;
    }
    public Date getMeFeRegistro() {
        return this.meFeRegistro;
    }
    
    public void setMeFeRegistro(Date meFeRegistro) {
        this.meFeRegistro = meFeRegistro;
    }
    public int getMeNuRango() {
        return this.meNuRango;
    }
    
    public void setMeNuRango(int meNuRango) {
        this.meNuRango = meNuRango;
    }
    public Set getDetalleMetricas() {
        return this.detalleMetricas;
    }
    
    public void setDetalleMetricas(Set detalleMetricas) {
        this.detalleMetricas = detalleMetricas;
    }




}


