package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer poIdProyectoPk;
     private Usuario usuario;
     private String poTxDescripcion;
     private Integer poIdEstado;
     private Date poFeRegistro;
     private Date poFeEjecucion;
     private Integer poIdMetodologia;
     private String poTxMotivo;
     private Set redEvaluacions = new HashSet(0);
     private Set relacions = new HashSet(0);
     private Set metricas = new HashSet(0);
     private Set cuestionarios = new HashSet(0);
     private Set cuestionarioEvaluados = new HashSet(0);
     private Set resultados = new HashSet(0);
     private Set participantes = new HashSet(0);
     private Set mensajes = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(Usuario usuario, String poTxDescripcion, Integer poIdEstado, Date poFeRegistro) {
        this.usuario = usuario;
        this.poTxDescripcion = poTxDescripcion;
        this.poIdEstado = poIdEstado;
        this.poFeRegistro = poFeRegistro;
    }
    public Proyecto(Usuario usuario, String poTxDescripcion, Integer poIdEstado, Date poFeRegistro, Date poFeEjecucion, Integer poIdMetodologia, Set redEvaluacions, Set relacions, Set metricas, Set cuestionarios, Set cuestionarioEvaluados, Set resultados, Set participantes, Set mensajes) {
       this.usuario = usuario;
       this.poTxDescripcion = poTxDescripcion;
       this.poIdEstado = poIdEstado;
       this.poFeRegistro = poFeRegistro;
       this.poFeEjecucion = poFeEjecucion;
       this.poIdMetodologia = poIdMetodologia;
       this.redEvaluacions = redEvaluacions;
       this.relacions = relacions;
       this.metricas = metricas;
       this.cuestionarios = cuestionarios;
       this.cuestionarioEvaluados = cuestionarioEvaluados;
       this.resultados = resultados;
       this.participantes = participantes;
       this.mensajes = mensajes;
    }
   
    
    public Integer getPoIdProyectoPk() {
        return this.poIdProyectoPk;
    }

    public String getPoTxMotivo() {
        return poTxMotivo;
    }

    public void setPoTxMotivo(String poTxMotivo) {
        this.poTxMotivo = poTxMotivo;
    }
    
    public void setPoIdProyectoPk(Integer poIdProyectoPk) {
        this.poIdProyectoPk = poIdProyectoPk;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPoTxDescripcion() {
        return this.poTxDescripcion;
    }
    
    public void setPoTxDescripcion(String poTxDescripcion) {
        this.poTxDescripcion = poTxDescripcion;
    }
    public Integer getPoIdEstado() {
        return this.poIdEstado;
    }
    
    public void setPoIdEstado(Integer poIdEstado) {
        this.poIdEstado = poIdEstado;
    }
    public Date getPoFeRegistro() {
        return this.poFeRegistro;
    }
    
    public void setPoFeRegistro(Date poFeRegistro) {
        this.poFeRegistro = poFeRegistro;
    }
    public Date getPoFeEjecucion() {
        return this.poFeEjecucion;
    }
    
    public void setPoFeEjecucion(Date poFeEjecucion) {
        this.poFeEjecucion = poFeEjecucion;
    }
    public Integer getPoIdMetodologia() {
        return this.poIdMetodologia;
    }
    
    public void setPoIdMetodologia(Integer poIdMetodologia) {
        this.poIdMetodologia = poIdMetodologia;
    }
    public Set getRedEvaluacions() {
        return this.redEvaluacions;
    }
    
    public void setRedEvaluacions(Set redEvaluacions) {
        this.redEvaluacions = redEvaluacions;
    }
    public Set getRelacions() {
        return this.relacions;
    }
    
    public void setRelacions(Set relacions) {
        this.relacions = relacions;
    }
    public Set getMetricas() {
        return this.metricas;
    }
    
    public void setMetricas(Set metricas) {
        this.metricas = metricas;
    }
    public Set getCuestionarios() {
        return this.cuestionarios;
    }
    
    public void setCuestionarios(Set cuestionarios) {
        this.cuestionarios = cuestionarios;
    }
    public Set getCuestionarioEvaluados() {
        return this.cuestionarioEvaluados;
    }
    
    public void setCuestionarioEvaluados(Set cuestionarioEvaluados) {
        this.cuestionarioEvaluados = cuestionarioEvaluados;
    }
    public Set getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Set resultados) {
        this.resultados = resultados;
    }
    public Set getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Set participantes) {
        this.participantes = participantes;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }




}


