package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA

/**
 * Contrato generated by hbm2java
 */
public class ReferenciaMovimiento implements java.io.Serializable {

    private Integer rmIdReferenciaMovPk;
    private String rmTxComentario;
    private Movimiento movimiento;
    private Integer poIdProyectoFk;

    public Integer getPoIdProyectoFk() {
        return poIdProyectoFk;
    }

    public void setPoIdProyectoFk(Integer poIdProyectoFk) {
        this.poIdProyectoFk = poIdProyectoFk;
    }
   
    public Integer getRmIdReferenciaMovPk() {
        return rmIdReferenciaMovPk;
    }

    public void setRmIdReferenciaMovPk(Integer rmIdReferenciaMovPk) {
        this.rmIdReferenciaMovPk = rmIdReferenciaMovPk;
    }

    public String getRmTxComentario() {
        return rmTxComentario;
    }

    public void setRmTxComentario(String rmTxComentario) {
        this.rmTxComentario = rmTxComentario;
    }

    public Movimiento getMovimiento() {
        return movimiento;
    }

    public void setMovimiento(Movimiento movimiento) {
        this.movimiento = movimiento;
    }

}
