package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA



/**
 * RelacionParticipanteId generated by hbm2java
 */
public class RelacionParticipanteId  implements java.io.Serializable {


     private Integer reIdRelacionFk;
     private Integer reIdParticipanteFk;
     private Integer paIdParticipanteFk;

    public RelacionParticipanteId() {
    }

    public RelacionParticipanteId(Integer reIdRelacionFk, Integer reIdParticipanteFk, Integer paIdParticipanteFk) {
       this.reIdRelacionFk = reIdRelacionFk;
       this.reIdParticipanteFk = reIdParticipanteFk;
       this.paIdParticipanteFk = paIdParticipanteFk;
    }
   
    public Integer getReIdRelacionFk() {
        return this.reIdRelacionFk;
    }
    
    public void setReIdRelacionFk(Integer reIdRelacionFk) {
        this.reIdRelacionFk = reIdRelacionFk;
    }
    public Integer getReIdParticipanteFk() {
        return this.reIdParticipanteFk;
    }
    
    public void setReIdParticipanteFk(Integer reIdParticipanteFk) {
        this.reIdParticipanteFk = reIdParticipanteFk;
    }
    public Integer getPaIdParticipanteFk() {
        return this.paIdParticipanteFk;
    }
    
    public void setPaIdParticipanteFk(Integer paIdParticipanteFk) {
        this.paIdParticipanteFk = paIdParticipanteFk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelacionParticipanteId) ) return false;
		 RelacionParticipanteId castOther = ( RelacionParticipanteId ) other; 
         
		 return (this.getReIdRelacionFk()==castOther.getReIdRelacionFk())
 && (this.getReIdParticipanteFk()==castOther.getReIdParticipanteFk())
 && (this.getPaIdParticipanteFk()==castOther.getPaIdParticipanteFk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getReIdRelacionFk();
         result = 37 * result + this.getReIdParticipanteFk();
         result = 37 * result + this.getPaIdParticipanteFk();
         return result;
   }   


}


