package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RelacionParticipante generated by hbm2java
 */
public class RelacionParticipante  implements java.io.Serializable {


     private RelacionParticipanteId id;
     private Relacion relacion;
     private Participante participante;
     private RedEvaluacion redEvaluacion;
     private Integer rpIdEstado;
     private Set resultados = new HashSet(0);

    public RelacionParticipante() {
    }

	
    public RelacionParticipante(RelacionParticipanteId id, Relacion relacion, Participante participante, RedEvaluacion redEvaluacion) {
        this.id = id;
        this.relacion = relacion;
        this.participante = participante;
        this.redEvaluacion = redEvaluacion;
    }
    public RelacionParticipante(RelacionParticipanteId id, Relacion relacion, Participante participante, RedEvaluacion redEvaluacion, Set resultados) {
       this.id = id;
       this.relacion = relacion;
       this.participante = participante;
       this.redEvaluacion = redEvaluacion;
       this.resultados = resultados;
    }

    public Integer getRpIdEstado() {
        return rpIdEstado;
    }

    public void setRpIdEstado(Integer rpIdEstado) {
        this.rpIdEstado = rpIdEstado;
    }
   
    
    public RelacionParticipanteId getId() {
        return this.id;
    }
    
    public void setId(RelacionParticipanteId id) {
        this.id = id;
    }
    public Relacion getRelacion() {
        return this.relacion;
    }
    
    public void setRelacion(Relacion relacion) {
        this.relacion = relacion;
    }
    public Participante getParticipante() {
        return this.participante;
    }
    
    public void setParticipante(Participante participante) {
        this.participante = participante;
    }
    public RedEvaluacion getRedEvaluacion() {
        return this.redEvaluacion;
    }
    
    public void setRedEvaluacion(RedEvaluacion redEvaluacion) {
        this.redEvaluacion = redEvaluacion;
    }
    public Set getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Set resultados) {
        this.resultados = resultados;
    }




}


