package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA



/**
 * Resultado generated by hbm2java
 */
public class Resultado  implements java.io.Serializable {


     private Integer reIdResultadoPk;
     private Componente componente;
     private DetalleMetrica detalleMetrica;
     private Proyecto proyecto;
     private String reTxComentario;
     
     private Integer reIdRelacionFk;
     private Integer reIdParticipanteFk;
     private Integer paIdParticipanteFk;
     private Integer coIdComponenteRefFk;
        
    public Resultado() {
    }

    public Resultado(RelacionParticipante relacionParticipante, Componente componente, Proyecto proyecto) {
        //this.relacionParticipante = relacionParticipante;
        this.componente = componente;
        this.proyecto = proyecto;
    }
    public Resultado(RelacionParticipante relacionParticipante, Componente componente, DetalleMetrica detalleMetrica, Proyecto proyecto, String reTxComentario) {
       //this.relacionParticipante = relacionParticipante;
       this.componente = componente;
       this.detalleMetrica = detalleMetrica;
       this.proyecto = proyecto;
       this.reTxComentario = reTxComentario;
    }

    
    public Integer getReIdRelacionFk() {
        return reIdRelacionFk;
    }

    public void setReIdRelacionFk(Integer reIdRelacionFk) {
        this.reIdRelacionFk = reIdRelacionFk;
    }

    public Integer getReIdParticipanteFk() {
        return reIdParticipanteFk;
    }

    public void setReIdParticipanteFk(Integer reIdParticipanteFk) {
        this.reIdParticipanteFk = reIdParticipanteFk;
    }

    public Integer getPaIdParticipanteFk() {
        return paIdParticipanteFk;
    }

    public void setPaIdParticipanteFk(Integer paIdParticipanteFk) {
        this.paIdParticipanteFk = paIdParticipanteFk;
    }
   
    public Integer getReIdResultadoPk() {
        return this.reIdResultadoPk;
    }
    
    public void setReIdResultadoPk(Integer reIdResultadoPk) {
        this.reIdResultadoPk = reIdResultadoPk;
    }
    public Componente getComponente() {
        return this.componente;
    }
    
    public void setComponente(Componente componente) {
        this.componente = componente;
    }
    public DetalleMetrica getDetalleMetrica() {
        return this.detalleMetrica;
    }
    
    public void setDetalleMetrica(DetalleMetrica detalleMetrica) {
        this.detalleMetrica = detalleMetrica;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getReTxComentario() {
        return this.reTxComentario;
    }
    
    public void setReTxComentario(String reTxComentario) {
        this.reTxComentario = reTxComentario;
    }

    public Integer getCoIdComponenteRefFk() {
        return coIdComponenteRefFk;
    }

    public void setCoIdComponenteRefFk(Integer coIdComponenteRefFk) {
        this.coIdComponenteRefFk = coIdComponenteRefFk;
    }

}


