package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;




/**
 * Resultado generated by hbm2java
 */
public class ResultadoInfo  implements java.io.Serializable {

     private BigDecimal deNuOrden;
     private String deTxValor;
     private String deNomRelacion;
     
     

    public BigDecimal getDeNuOrden() {
        return deNuOrden;
    }

    public String getDeNomRelacion() {
        return deNomRelacion;
    }

    public void setDeNomRelacion(String deNomRelacion) {
        this.deNomRelacion = deNomRelacion;
    }

    public void setDeNuOrden(BigDecimal deNuOrden) {
        this.deNuOrden = deNuOrden;
    }

   

    public String getDeTxValor() {
        return deTxValor;
    }

    public void setDeTxValor(String deTxValor) {
        this.deTxValor = deTxValor;
    }
     
     
}   
        
    

