package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarifa generated by hbm2java
 */
public class Tarifa  implements java.io.Serializable {


     private Integer taIdTarifaPk;
     private String taTxDescripcion;
     private BigDecimal taDePrecio;
     private int taIdTipoTarifa;
     private Date taFeCreacion;
     private int taIdEstado;
     private String taTxPrefijo;
     private Set contratos = new HashSet(0);

    public Tarifa() {
    }

	
    public Tarifa(String taTxDescripcion, BigDecimal taDePrecio, Date taFeCreacion, int taIdEstado) {
        this.taTxDescripcion = taTxDescripcion;
        this.taDePrecio = taDePrecio;
        this.taFeCreacion = taFeCreacion;
        this.taIdEstado = taIdEstado;
    }
    public Tarifa(String taTxDescripcion, BigDecimal taDePrecio, Date taFeCreacion, int taIdEstado, Set contratos) {
       this.taTxDescripcion = taTxDescripcion;
       this.taDePrecio = taDePrecio;
       this.taFeCreacion = taFeCreacion;
       this.taIdEstado = taIdEstado;
       this.contratos = contratos;
    }
   
    public Integer getTaIdTarifaPk() {
        return this.taIdTarifaPk;
    }

    public String getTaTxPrefijo() {
        return taTxPrefijo;
    }

    public void setTaTxPrefijo(String taTxPrefijo) {
        this.taTxPrefijo = taTxPrefijo;
    }
    
    
    public void setTaIdTarifaPk(Integer taIdTarifaPk) {
        this.taIdTarifaPk = taIdTarifaPk;
    }
    public String getTaTxDescripcion() {
        return this.taTxDescripcion;
    }
    
    public void setTaTxDescripcion(String taTxDescripcion) {
        this.taTxDescripcion = taTxDescripcion;
    }
    public BigDecimal getTaDePrecio() {
        return this.taDePrecio;
    }
    
    public void setTaDePrecio(BigDecimal taDePrecio) {
        this.taDePrecio = taDePrecio;
    }
    public Date getTaFeCreacion() {
        return this.taFeCreacion;
    }
    
    public void setTaFeCreacion(Date taFeCreacion) {
        this.taFeCreacion = taFeCreacion;
    }
    public int getTaIdEstado() {
        return this.taIdEstado;
    }
    
    public void setTaIdEstado(int taIdEstado) {
        this.taIdEstado = taIdEstado;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }

    public int getTaIdTipoTarifa() {
        return taIdTipoTarifa;
    }

    public void setTaIdTipoTarifa(int taIdTipoTarifa) {
        this.taIdTipoTarifa = taIdTipoTarifa;
    }

}


