package com.jaio360.orm;
// Generated 21/10/2014 08:38:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ubigeo generated by hbm2java
 */
public class Ubigeo  implements java.io.Serializable {


     private int ubIdUbigeoPk;
     private Ubigeo ubigeo;
     private String ubTxDescripcion;
     private int ubIdTipoUbigeo;
     private Set ubigeos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Ubigeo() {
    }

	
    public Ubigeo(int ubIdUbigeoPk, String ubTxDescripcion, int ubIdTipoUbigeo) {
        this.ubIdUbigeoPk = ubIdUbigeoPk;
        this.ubTxDescripcion = ubTxDescripcion;
        this.ubIdTipoUbigeo = ubIdTipoUbigeo;
    }
    public Ubigeo(int ubIdUbigeoPk, Ubigeo ubigeo, String ubTxDescripcion, int ubIdTipoUbigeo, Set ubigeos, Set usuarios) {
       this.ubIdUbigeoPk = ubIdUbigeoPk;
       this.ubigeo = ubigeo;
       this.ubTxDescripcion = ubTxDescripcion;
       this.ubIdTipoUbigeo = ubIdTipoUbigeo;
       this.ubigeos = ubigeos;
       this.usuarios = usuarios;
    }
   
    public int getUbIdUbigeoPk() {
        return this.ubIdUbigeoPk;
    }
    
    public void setUbIdUbigeoPk(int ubIdUbigeoPk) {
        this.ubIdUbigeoPk = ubIdUbigeoPk;
    }
    public Ubigeo getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(Ubigeo ubigeo) {
        this.ubigeo = ubigeo;
    }
    public String getUbTxDescripcion() {
        return this.ubTxDescripcion;
    }
    
    public void setUbTxDescripcion(String ubTxDescripcion) {
        this.ubTxDescripcion = ubTxDescripcion;
    }
    public int getUbIdTipoUbigeo() {
        return this.ubIdTipoUbigeo;
    }
    
    public void setUbIdTipoUbigeo(int ubIdTipoUbigeo) {
        this.ubIdTipoUbigeo = ubIdTipoUbigeo;
    }
    public Set getUbigeos() {
        return this.ubigeos;
    }
    
    public void setUbigeos(Set ubigeos) {
        this.ubigeos = ubigeos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


